name: bfems
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  image_picker: ^1.1.2 #image picker for mobile app
  file_picker: ^9.0.2 #file picker for desktop app
  # image_picker_android: ^0.8.12+21
  # image_picker_for_web: ^3.0.6
  fl_chart: ^0.70.2 
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  path: ^1.7.0
  intl: ^0.20.1
  http: ^1.3.0
  http_parser: ^4.0.2
  flutter_map: ^8.1.0
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.1.0
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  #mapbox_gl: ^0.16.0
  #geolocator: ^10.1.0
  #geocoding: ^2.1.0



flutter:
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf

  
  uses-material-design: true

  